import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import Providers from "@/components/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
        <nav className="w-full flex justify-end gap-4 p-4 border-b">
          {session ? (
            <form action="/api/auth/signout" method="post">
              <button className="text-sm hover:underline">Sair</button>
            </form>
          ) : (
            <>
              <Link href="/login" className="text-sm hover:underline">
                Entrar
              </Link>
              <Link href="/register" className="text-sm hover:underline">
                Criar conta
              </Link>
            </>
          )}
        </nav>
        {children}
        </Providers>
      </body>
    </html>
  );
}
